templates:
- name: "dir"
  {{if has . "OUTPUT_PATH"}}
  output_path: "{{.OUTPUT_PATH}}"
  {{else}}
  output_path: "./project.{{.PROJECT_ID}}"
  {{end}}
- name: "terragrunt"
  component_path: "../../components/terragrunt/leaf"
  output_ref: "dir"
  output_path: "./project"
- name: "project"
  component_path: "../../components/project/project"
  output_ref: "terragrunt"

{{if has . "RESOURCES"}}
- name: "resources"
  recipe_path: "../project/resources.yaml"
  output_ref: "dir"
  output_path: "./resources"
  flatten:
  - key: "RESOURCES"
{{end}}

{{if index . "PROJECT_OWNERS"}}
- name: "owners"
  component_path: "../../components/project/owners"
  output_ref: "dir"
{{end}}
