templates:
- name: "dir"
  output_path: "./project.{{.PROJECT_ID}}"
- name: "project"
  recipe_path: "../org/project.yaml"
  data:
    DEPS:
    - NAME: "parent_folder"
      PATH: "../../folder"
      MOCK_OUTPUTS:
        name: '"mock-folder"'
    INPUTS:
      folder_id: "dependency.parent_folder.outputs.name"
