# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Required fields
template_dir: ../../templates/policygen
org_id: "12345678"

# Optional fields
forseti_policies: {}
gcp_organization_policies:
  PARENT_TYPE: organization # one of `organization`, `folder` or `project`
  PARENT_ID: "12345678"
  ALLOWED_POLICY_MEMBER_DOMAINS:
  - google.com
  ALLOWED_SHARED_VPC_HOST_PROJECTS:
  - under:organizations/12345678
